import Foundation

public enum CapturePolicy {
    public static let ignoredTypes: Set<String> = [
        "org.nspasteboard.ConcealedType", "org.nspasteboard.TransientType",
        "org.nspasteboard.AutoGeneratedType", "com.agilebits.onepassword",
        "de.petermaurer.TransientPasteboardType", "com.typeit4me.clipping",
        "Pasteboard generator type"
    ]
    public static let defaultExcludedApps: Set<String> = [
        "com.1password.1password", "com.agilebits.onepassword7", "com.bitwarden.desktop",
        "com.apple.Passwords", "com.dashlane.Dashlane", "com.lastpass.LastPass"
    ]

    public static func allows(types: Set<String>, sourceBundleID: String?, excludedApps: Set<String>) -> Bool {
        guard types.isDisjoint(with: ignoredTypes) else { return false }
        return sourceBundleID.map { !excludedApps.contains($0) } ?? true
    }
}
